### ISSUE TITLE
Source linting

### ISSUE THREAD

**Issue by Almeida-a** [iByteABit256/Vivace#5]
Hello, thank you for publishing this interesting project!

I have a suggestion for using the `cargo fmt` and `clippy` tools on the project's source code, in order to have some standardized styling to it.

@iByteABit256 I don't know what policy you want to have on this subject, and since I noticed your own code style, you might want to stick to it. If so, you can configure your fmt style on a `rustfmt.toml` file (see [more](https://www.reddit.com/r/rust/comments/9jl6a9/pro_tip_if_you_use_cargo_fmtrustfmt_use_a/)), if you still want to enforce uniform style throughout the project.

**Comment by iByteABit256** [comment]
That's a good idea, thank you!

I'll be in vacation for a week but I'll add it when I come back

**Comment by Almeida-a** [comment]
You're welcome!

In the meantime I can submit a pr with the changes suggested by `clippy`, if you allow!

**Comment by iByteABit256** [comment]
Of course!
